version: '2'

services:

  session:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - session:/data
    networks:
      - network

  database:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: vesta

  api:
    image: node
    ports:
      - '3000:3000'
      - '5858:5858'
      - '9229:9229'
    volumes:
      - ../..:/app
      - storage:/upload
      - ../../resources/log:/log
    networks:
      - network
    working_dir: /app/vesta/server
    command: npm run api
    environment:
      NODE_ENV: development
      LOG_LEVEL: 5
      PORT: 3000
      SDB_PROTOCOL: redis
      SDB_HOST: session
      SDB_PORT: 6379
      ADB_PROTOCOL: mysql
      ADB_HOST: database
      ADB_PORT: 3306
      ADB_USERNAME: root
      ADB_PASSWORD:
      ADB_NAME: vesta
      SALT: '__SALT__'
      SECRET_KEY: '__SECRET_KEY__'
    depends_on:
      - session
      - database

volumes:
  session:
  database:
  storage:

networks:
  network:
